name: Main Branch

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: niranjan2519/dotnet-ci-cd/.github/workflows/ci.yml@main
    with:
      token: ${{ secrets.PAT_TOKEN }}
  
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-22.04
    environment: main
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven Verify
        run: mvn -B clean verify

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-22.04
    environment: main
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-22.04
    needs: [test, sonar]
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml