name: Main Branch

on:
  push:
    branches:
      - 'main'

jobs:
  
  build:
    uses: .github/workflows.github/workflows/ci.yml
  
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-22.04
    environment: main
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn -B clean package 
      - name: Maven Verify
        run: mvn -B clean verify 

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-22.04
    environment: main
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://tired-garlics-grow-49-37-215-196.loca.lt
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=devops -Dsonar.host.url=https://tired-garlics-grow-49-37-215-196.loca.lt -Dsonar.login=sqp_0a98899f49ddd772b243a815b69e77b5404c8e1e
